# Generated by Django 5.0.4 on 2024-05-03 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_design_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 100 characters or fewer. Letters, digits, and spaces only.', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='The username may contain alphanumeric characters and spaces only.', regex='^[\\w\\s]+$')]),
        ),
    ]
