# Generated by Django 5.0.4 on 2024-05-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_design_auth', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organisation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
