# Generated by Django 5.0.4 on 2024-07-31 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_design_auth', '0005_alter_customuser_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 100 characters or fewer. Letters, digits, and spaces only.', max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='The username may contain alphanumeric characters, hyphens, underscores, "@", and "." only.', regex='^[\\w@.-]+$')], verbose_name='username'),
        ),
    ]
