# Generated by Django 5.0.4 on 2024-08-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('project_id', models.CharField(default='', editable=False, max_length=12, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_type', models.CharField(choices=[('WC', 'Wind Comfort'), ('WE', 'Wind Energy'), ('TC', 'Thermal Comfort'), ('AQ', 'Air Quality')], max_length=2)),
                ('analysis_option', models.CharField(choices=[('Lawson', 'Lawson'), ('NEN8100', 'NEN8100')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('collaborators', models.TextField(blank=True, help_text='Comma-separated list of collaborator emails')),
                ('building_of_interest_stl', models.BinaryField(blank=True, null=True)),
                ('surroundings_stl', models.BinaryField(blank=True, null=True)),
                ('terrain_stl', models.BinaryField(blank=True, null=True)),
                ('simulation_data_vtp', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
